Repository WildCodeSchool-2024-02/PHP-REM-POEC-05-MidiATech, pull requests merged in 2024-07, with the labels that each got.

#14 S02 mk50 trie resultat
  database.sql
  public/assets/css/category_dropdown.css
  public/assets/css/medias.css
  public/assets/images/covers/1984.jpg
  public/assets/images/covers/chevaliers_emeraude.jpg
  public/assets/images/covers/dune.jpg
  public/assets/images/covers/eragon.jpg
  public/assets/images/covers/ewilan.jpg
  public/assets/images/covers/fight_club.jpg
  public/assets/images/covers/forrest_gump.jpg
  public/assets/images/covers/gladiator.jpg
  public/assets/images/covers/harry_potter.jpg
  public/assets/images/covers/hunger_games.jpg
  public/assets/images/covers/inception.jpg
  public/assets/images/covers/interstellar.jpg
  public/assets/images/covers/la_belle_et_la_bete.jpg
  public/assets/images/covers/la_passe_miroir.jpg
  public/assets/images/covers/la_roue_du_temps.jpg
  public/assets/images/covers/la_selection.jpg
  public/assets/images/covers/le_clan_des_otori.jpg
  public/assets/images/covers/le_hobbit.jpg
  public/assets/images/covers/le_labyrinthe.jpg
  public/assets/images/covers/le_nom_de_la_rose.jpg
  public/assets/images/covers/le_petit_prince.jpg
  public/assets/images/covers/le_seigneur_des_anneaux.jpg
  public/assets/images/covers/les_miserables.jpg
  public/assets/images/covers/letranger.jpg
  public/assets/images/covers/millenium.jpg
  public/assets/images/covers/narnia.jpg
  public/assets/images/covers/nos_etoiles_contraires.jpg
  public/assets/images/covers/orgueil_prejuges_zombies.jpg
  public/assets/images/covers/outlander.jpg
  public/assets/images/covers/percy_jackson.jpg
  public/assets/images/covers/pride_and_prejudice.jpg
  public/assets/images/covers/pulp_fiction.jpg
  public/assets/images/covers/romeo_et_juliette.jpg
  public/assets/images/covers/sapiens.jpg
  public/assets/images/covers/shawshank_redemption.jpg
  public/assets/images/covers/the_dark_knight.jpg
  public/assets/images/covers/the_godfather.jpg
  public/assets/images/covers/the_matrix.jpg
  public/assets/images/covers/twilight.jpg
  public/assets/javascript/filters.js
  src/Controller/BooksController.php
  src/Controller/MusicsController.php
  src/Controller/UserController.php
  src/Controller/VideosController.php
  src/Model/BooksManager.php
  src/Model/CategoriesManager.php
  src/Model/MusicsManager.php
  src/Model/VideosManager.php
  src/View/Media/index.html.twig
  src/View/Profile/inscription.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#16 correction bug data
  database.sql
Labels: CORRECTIONS DONE, REVIEW REQUESTED

#17 S04 mt60 afficher info perso
  database.sql
  public/assets/css/editProfil.css
  public/assets/css/medias.css
  public/assets/css/profile.css
  public/assets/images/profile.jpg
  public/assets/javascript/filters.js
  src/Controller/BooksController.php
  src/Controller/BrrowingController.php
  src/Controller/MusicsController.php
  src/Controller/UserController.php
  src/Controller/VideosController.php
  src/Model/BorrowingManager.php
  src/Model/TypesManager.php
  src/Model/UserManager.php
  src/Model/VideosManager.php
  src/View/Base/_header.html.twig
  src/View/Media/index.html.twig
  src/View/Profile/editProfile.html.twig
  src/View/Profile/profile.html.twig
  src/routes.php
Labels: CORRECTIONS DONE, REVIEWED

#18 S02 mt32 index
  database.sql
  public/assets/css/home.css
  public/assets/javascript/home.js
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#21 reservation dun media par utilisateur fonctionnel
  src/Controller/BorrowingController.php
  src/Controller/BrrowingController.php
  src/Controller/UserController.php
  src/Model/BorrowingManager.php
  src/View/Account/index.html.twig
  src/View/Media/show.html.twig
  src/routes.php
Labels: REVIEWED

#22 optimisation et correction
  composer.json
  composer.lock
  config/di.php
  public/assets/css/home.css
  public/assets/javascript/base.js
  public/assets/javascript/home.js
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/AdminController.php
  src/Controller/BooksController.php
  src/Controller/BorrowingController.php
  src/Controller/ConnectController.php
  src/Controller/HomeController.php
  src/Controller/MusicsController.php
  src/Controller/SearchController.php
  src/Controller/UserController.php
  src/Controller/VideosController.php
  src/Model/AbstractManager.php
  src/Model/SessionManager.php
  src/Service/ManagerRegistry.php
  src/View/Home/index.html.twig
  src/View/Media/index.html.twig
  src/View/layout.html.twig
  src/routes.php
  src/routing.php
  tests/controllers/HomeControllerTest.php.dist
  tests/controllers/test.php
  tests/models/ItemManagerTest.php.dist
  tests/models/test.php
Labels: REVIEW REQUESTED
