Repository WildCodeSchool-2024-02/PHP-REM-POEC-05-MidiATech, pull requests merged in 2024-08, with the labels that each got.

#23 S03 mt55 gestionreservations
  database.sql
  public/assets/css/admin.css
  public/assets/css/collections.css
  public/assets/css/index.css
  public/assets/css/profile.css
  public/assets/css/reservations.css
  public/assets/css/stocks.css
  src/Controller/AbstractController.php
  src/Controller/AdminController.php
  src/Controller/BorrowingController.php
  src/Model/AbstractManager.php
  src/Model/BooksManager.php
  src/Model/BorrowingManager.php
  src/Model/CollectionsManager.php
  src/Model/MusicsManager.php
  src/Model/TypesManager.php
  src/Model/UserManager.php
  src/Model/VideosManager.php
  src/View/Account/index.html.twig
  src/View/Admin/admin.html.twig
  src/View/Admin/collections.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/reservations.html.twig
  src/View/Admin/stocks.html.twig
  src/routes.php
Labels: REVIEWED

#24 Demo
  public/assets/css/base.css
  public/assets/css/home.css
  public/assets/css/inscription.css
  public/assets/css/login.css
  public/assets/css/reservations.css
  public/assets/css/show.css
  public/assets/css/stocks.css
  public/assets/javascript/home.js
  public/assets/javascript/login.js
  public/assets/javascript/register.js
  src/Controller/ConnectController.php
  src/Model/UserManager.php
  src/View/Account/login.html.twig
  src/View/Account/register.html.twig
  src/View/Base/_footer.html.twig
  src/View/Home/index.html.twig
  src/View/Media/index.html.twig
  src/View/Media/show.html.twig
  src/routes.php
Labels: CORRECTIONS DONE, REVIEWED

#25 Gestion categorie
  database.sql
  public/assets/css/categories.css
  public/assets/css/collections.css
  src/Controller/AbstractController.php
  src/Controller/AdminBooksController.php
  src/Controller/AdminController.php
  src/Controller/AdminMusicsController.php
  src/Controller/AdminVideosController.php
  src/Controller/BooksController.php
  src/Controller/MusicsController.php
  src/Controller/VideosController.php
  src/Controller/VideosTypesController.php
  src/Model/AbstractManager.php
  src/Model/AdminManager.php
  src/Model/BooksManager.php
  src/Model/VideosManager.php
  src/Service/ManagerRegistry.php
  src/Trait/MediasTrait.php
  src/View/Admin/_form.html.twig
  src/View/Admin/add.html.twig
  src/View/Admin/admin.html.twig
  src/View/Admin/categories.html.twig
  src/View/Admin/categoriesMedias.html.twig
  src/View/Admin/collections.html.twig
  src/View/Admin/edit.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED

#26 correction done
  database.sql
  public/assets/css/home.css
  src/Controller/BooksController.php
  src/Controller/MusicsController.php
  src/Controller/VideosController.php
  src/Model/BooksManager.php
  src/Model/CategoriesManager.php
  src/Model/MusicsManager.php
  src/Model/VideosManager.php
  src/View/Account/index.html.twig
  src/View/Media/_form.html.twig
  src/View/Media/index.html.twig
Labels: REVIEWED

#27 admin categories polissage
  public/assets/css/base.css
  public/assets/css/index.css
  src/Controller/BooksController.php
  src/Controller/MusicsController.php
  src/Controller/VideosController.php
  src/View/Admin/categoriesMedias.html.twig
Labels: REVIEWED

#30 ajustements
  public/assets/css/profile.css
  src/Controller/BooksController.php
  src/Controller/MusicsController.php
  src/Controller/UserController.php
  src/View/Account/index.html.twig
Labels: REVIEW REQUESTED

#31 Branch test
  public/assets/css/admin.css
  public/assets/css/inscription.css
  public/assets/css/login.css
  src/View/Home/index.html.twig
Labels: REVIEWED

#32 QoL
  src/View/Media/show.html.twig
Labels: REVIEWED
